### ISSUE TITLE
Epic: Comprehensive example notebooks

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#108]
We are currently writing user stories and example code that a user would execute to do these things. We should have 1 example for each user story and ensure that the examples that we do have are intended use cases of the project.

**Comment by aimalz** [comment]
This issue can be closed when folks are satisfied with any subset of the following issues: 
- [ ] #96 Import DESC input data format to minimal pipeline procedure
- [ ] #126 Notebook for cluster mass via p(z) catalog
- [ ] #129 Notebook for miscentering exploration 
- [ ] #130 Notebook for cluster mass via color cut method

**Comment by cavestruz** [comment]
@aimalz - Are the previous notebooks v1.0, or should they be enhancements?  Miscentering could be done, and @combet is looking at that with her student - clustertoolkit has miscentering capability.  But, this may or may not be v1.0 appropriate as well.

**Comment by aimalz** [comment]
I think this has been satisfied by the [0.9.* releases](https://github.com/LSSTDESC/CLMM/releases). Since we've successfully set a standard of this kind of comprehensive demo being part of the process for any scope expansions and new feature additions, I'm going to close this issue. (If I'm mistaken, please feel free to reopen it!)
