### ISSUE TITLE
Refactor base clmm code.

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#112]
Refactoring base clmm code to updated framework for minimal example. This issue depends on several other issues.

- [ ]  Issue #110: Refactoring GalaxyCluster object
- [ ]  Issue #111: Refactoring mode definition
- [ ]  Issue #114: Re-write/replace ShearAzimuthalAverager
- [x]  Issue #103: Move from astropy to CCL in ShearAzimuthalAverager
- [ ]  Issue #93: Add informative functions in GalaxyCluster
- [ ]  Issue #65: Status of GCData object
- [ ]  Issue #19: Adhering to the style guide
- [ ] Delete `crypt` directories both in code and tests.
- [ ] Delete --ignore in `.travis.yml`, `setup.py`, and `docs/conf.py`

**Comment by aimalz** [comment]
I checked off #103 because it's taken care of by #114, which is currently in progress.
